SELECT * FROM routes;
SELECT * FROM transport_types;
SELECT * FROM trips;
SELECT * FROM participants;
SELECT * FROM guides;
SELECT * FROM trip_participants;
SELECT * FROM schedules;
SELECT * FROM events;
SELECT * FROM actions;